In [285]:
import pandas as pd
import tensorflow as tf
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from keras.layers.core import Dense, Activation
from keras.models import Sequential
from keras.callbacks import EarlyStopping
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


In [286]:
def dummies(df, name):
    dummy = pd.get_dummies(df[name])
    for x in dummy.columns:
        dummy_name = f"{name}-{x}"
        df[dummy_name] = dummy[x]
    df.drop(name, axis=1, inplace=True)

In [287]:
df = pd.read_csv("kddcup.data_10_percent_corrected", header = None)

In [288]:
df.columns = [
    'duration',
    'protocol_type',
    'service',
    'flag',
    'src_bytes',
    'dst_bytes',
    'land',
    'wrong_fragment',
    'urgent',
    'hot',
    'num_failed_logins',
    'logged_in',
    'num_compromised',
    'root_shell',
    'su_attempted',
    'num_root',
    'num_file_creations',
    'num_shells',
    'num_access_files',
    'num_outbound_cmds',
    'is_host_login',
    'is_guest_login',
    'count',
    'srv_count',
    'serror_rate',
    'srv_serror_rate',
    'rerror_rate',
    'srv_rerror_rate',
    'same_srv_rate',
    'diff_srv_rate',
    'srv_diff_host_rate',
    'dst_host_count',
    'dst_host_srv_count',
    'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate',
    'dst_host_srv_serror_rate',
    'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate',
    'outcome'
]

df[0:5]

duration protocol_type service flag  src_bytes  dst_bytes  land  \
0         0           tcp    http   SF        181       5450     0   
1         0           tcp    http   SF        239        486     0   
2         0           tcp    http   SF        235       1337     0   
3         0           tcp    http   SF        219       1337     0   
4         0           tcp    http   SF        217       2032     0   

   wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0               0       0    0  ...                   9   
1               0       0    0  ...                  19   
2               0       0    0  ...                  29   
3               0       0    0  ...                  39   
4               0       0    0  ...                  49   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   
1                     1.0                     0.0   
2                     1.0                     0.0   
3                     1.0                     0.0   
4                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                          0.0   
1                         0.05                          0.0   
2                         0.03                          0.0   
3                         0.03                          0.0   
4                         0.02                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  outcome  
0                       0.0  normal.  
1                       0.0  normal.  
2                       0.0  normal.  
3                       0.0  normal.  
4                       0.0  normal.  

[5 rows x 42 columns]

In [289]:
#df['target'] = df['outcome'] != 'normal.'
#df = df.drop('outcome', axis=1)

#feature n outcome 

#x = df.drop('outcome', axis = 1)
y = df[['outcome']]
#convert outcome to integers

dummy = pd.get_dummies(y['outcome'])
y = dummy.values


y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [290]:
dummies(df,'protocol_type')
dummies(df, 'service')
dummies(df, 'flag')

df[0:5]

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0         0        181       5450     0               0       0    0   
1         0        239        486     0               0       0    0   
2         0        235       1337     0               0       0    0   
3         0        219       1337     0               0       0    0   
4         0        217       2032     0               0       0    0   

   num_failed_logins  logged_in  num_compromised  ...  flag-REJ  flag-RSTO  \
0                  0          1                0  ...         0          0   
1                  0          1                0  ...         0          0   
2                  0          1                0  ...         0          0   
3                  0          1                0  ...         0          0   
4                  0          1                0  ...         0          0   

   flag-RSTOS0  flag-RSTR  flag-S0  flag-S1  flag-S2  flag-S3  flag-SF  \
0            0          0        0        0        0        0        1   
1            0          0        0        0        0        0        1   
2            0          0        0        0        0        0        1   
3            0          0        0        0        0        0        1   
4            0          0        0        0        0        0        1   

   flag-SH  
0        0  
1        0  
2        0  
3        0  
4        0  

[5 rows x 119 columns]

In [291]:
x = df


#Outcomes - Turning into Dummy variables as string cantnot passs through an array into the neural net.
#dummies = pd.get_dummies(y['target'])
#y = dummies.values

#df = pd.DataFrame(x)

#f[0:5]



In [294]:
x

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        181       5450     0               0       0    0   
1              0        239        486     0               0       0    0   
2              0        235       1337     0               0       0    0   
3              0        219       1337     0               0       0    0   
4              0        217       2032     0               0       0    0   
5              0        217       2032     0               0       0    0   
6              0        212       1940     0               0       0    0   
7              0        159       4087     0               0       0    0   
8              0        210        151     0               0       0    0   
9              0        212        786     0               0       0    1   
10             0        210        624     0               0       0    0   
11             0        177       1985     0               0       0    0   
12             0        222        773     0               0       0    0   
13             0        256       1169     0               0       0    0   
14             0        241        259     0               0       0    0   
15             0        260       1837     0               0       0    0   
16             0        241        261     0               0       0    0   
17             0        257        818     0               0       0    0   
18             0        233        255     0               0       0    0   
19             0        233        504     0               0       0    0   
20             0        256       1273     0               0       0    0   
21             0        234        255     0               0       0    0   
22             0        241        259     0               0       0    0   
23             0        239        968     0               0       0    0   
24             0        245       1919     0               0       0    0   
25             0        248       2129     0               0       0    0   
26             0        354       1752     0               0       0    0   
27             0        193       3991     0               0       0    0   
28             0        214      14959     0               0       0    0   
29             0        212       1309     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
493991         0        296        617     0               0       0    0   
493992         0        294      29288     0               0       0    0   
493993         0        285      34557     0               0       0    0   
493994         0        316       3665     0               0       0    0   
493995         0        335      10440     0               0       0    0   
493996         0        284      10592     0               0       0    0   
493997         0        242       7066     0               0       0    0   
493998         0        223       3707     0               0       0    0   
493999         0        204       1731     0               0       0    0   
494000         0        148       1122     0               0       0    0   
494001         0          0          0     0               0       0    0   
494002         0        215       2649     0               0       0    0   
494003         0        341        326     0               0       0    0   
494004         0        341       1943     0               0       0    0   
494005         0        341       1663     0               0       0    0   
494006         0        235        501     0               0       0    0   
494007         0        320      13828     0               0       0    0   
494008         0        319       1435     0               0       0    0   
494009         0        335       3435     0               0       0    0   
494010         0        291        236     0               0       0    0   
4940

In [214]:
#Turn categorical data into intergers of 0 & 1 

dummies = pd.get_dummies(df['protocol_type'],['service'],['flag'],['land'])

#drop as column is now encoded
#x = df.drop(['target'], axis = 1)

#concat dummy values to the dataframe

x = x.join(dummies)


x[0:5]

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0         0        239        486     0               0       0    0   
1         0        235       1337     0               0       0    0   
2         0        219       1337     0               0       0    0   
3         0        217       2032     0               0       0    0   
4         0        217       2032     0               0       0    0   

   num_failed_logins  logged_in  num_compromised  ...  \
0                  0          1                0  ...   
1                  0          1                0  ...   
2                  0          1                0  ...   
3                  0          1                0  ...   
4                  0          1                0  ...   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.05                          0.0   
1                         0.03                          0.0   
2                         0.03                          0.0   
3                         0.02                          0.0   
4                         0.02                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  ['service']['flag']icmp  ['service']['flag']tcp  \
0                       0.0                        0                       1   
1                       0.0                        0                       1   
2                       0.0                        0                       1   
3                       0.0                        0                       1   
4                       0.0                        0                       1   

   ['service']['flag']udp  ['service']['flag']nan  
0                       0                       0  
1                       0                       0  
2                       0                       0  
3                       0                       0  
4                       0                       0  

[5 rows x 42 columns]

In [293]:
# Get column names first
#names = df.columns
# Create the Scaler object
scaler = preprocessing.StandardScaler()
# Fit data on the scaler object
scaled_df = scaler.fit_transform(x)
#scaled_df = pd.DataFrame(scaled_df, columns=names)
x = scaled_df
#x = pd.DataFrame(scaled_df)

x[0:5]

ValueError: could not convert string to float: 'normal.'

In [201]:
#Perform PCA to reduce dimensionality of feature vector for better accuracy
#reduce from 37 to 2 dimensional space

pca=PCA(n_components = 2)
pca.fit(x)
x_scaled = pca.transform(x)
print ("Original Shape:   ", x.shape)
print ("Transformed Shape:",x_scaled.shape)

x = x_scaled

print(x)

Original Shape:    (494021, 119)
Transformed Shape: (494021, 2)
[[1.12677239 4.36570367]
 [1.12811941 4.34210149]
 [1.10953775 4.31167313]
 ...
 [0.7854045  4.63766621]
 [0.61762622 4.77191391]
 [0.5103421  4.79523379]]


In [348]:

x_train


array([[ 1.00146943,  2.02430989],
       [-2.67759226, -0.61415085],
       [ 2.20345277,  5.07488625],
       ...,
       [-2.67759226, -0.61415085],
       [ 1.29200402,  1.22337951],
       [ 6.25652783, -2.96399323]])

In [204]:
# Create a test/train split, testing on 25% of data. 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=45)

In [213]:
from sklearn.neural_network import MLPClassifier

classifier = MLPClassifier(hidden_layer_sizes=(50,100,50), 
                           activation = 'relu',solver='adam', 
                           max_iter = 10, early_stopping= True,learning_rate = 'constant',
                           alpha = 0.0001, momentum = 0.2,tol=0.0001,
                           verbose = True, n_iter_no_change = 10)
#Uses Log Loss function
#same as Categorical 

In [214]:
classifier.fit(x_train, y_train)

Iteration 1, loss = 0.08271688
Validation score: 0.991525
Iteration 2, loss = 0.04371081
Validation score: 0.993766
Iteration 3, loss = 0.03702883
Validation score: 0.993388
Iteration 4, loss = 0.03481014
Validation score: 0.993900
Iteration 5, loss = 0.03365095
Validation score: 0.994008
Iteration 6, loss = 0.03301512
Validation score: 0.993064
Iteration 7, loss = 0.03256652
Validation score: 0.993900
Iteration 8, loss = 0.03194983
Validation score: 0.993280
Iteration 9, loss = 0.03179675
Validation score: 0.993873
Iteration 10, loss = 0.03134865
Validation score: 0.994494


C:\Users\avmas\Miniconda3\envs\tensorflow\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=True, epsilon=1e-08,
              hidden_layer_sizes=(50, 100, 50), learning_rate='constant',
              learning_rate_init=0.001, max_iter=10, momentum=0.2,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=True, warm_start=False)

In [215]:
#Predicting y for x_validation
y_pred = classifier.predict(x_test)

In [216]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred.argmax(axis=1),y_test.argmax(axis=1))

In [217]:
cm

array([[24218,   638],
       [   49, 98601]], dtype=int64)

In [210]:
TP = 24041
TN = 420
FP = 226
FN = 98819

In [211]:
Acc = ((TP + TN)/(TP + TN + FP + FN))

print( "Accuracy", Acc)

Accuracy 0.19805515521513126


In [244]:
# Recall 

Recall = ((TP)/(TP + FN))

print("Recall", Recall)

Recall 0.19646439113488479


In [245]:
# Precision

Precision = ((TP)/(TP+FP))

print("Precision", Precision)

Precision 0.9921350627959646


In [212]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     24460
           1       1.00      1.00      1.00     99059

   micro avg       0.99      0.99      0.99    123519
   macro avg       0.99      0.99      0.99    123519
weighted avg       0.99      0.99      0.99    123519
 samples avg       0.99      0.99      0.99    123519



C:\Users\avmas\Miniconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels.
  'recall', 'true', average, warn_for)


In [109]:
# Break into X (predictors) & y (prediction)
#x, y = to_xy(df,'outcome')

# Create a test/train split.  25% test
# Split into train/test
#x_train, x_test, y_train, y_test = train_test_split(
 #   x_pca, Y, test_size=0.25, random_state=42)

# Create neural net
model = Sequential()
model.add(Dense(100, input_dim=X.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(50, input_dim=X.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(25, input_dim=X.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(12, input_dim=X.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))
model.add(Dense(y.shape[1],activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto')
model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=1000)


Train on 370515 samples, validate on 123505 samples
Epoch 1/1000
 - 78s - loss: 0.0975 - val_loss: 0.0414
Epoch 2/1000
 - 27s - loss: 0.0388 - val_loss: 0.0353
Epoch 3/1000
 - 28s - loss: 0.0316 - val_loss: 0.0324
Epoch 4/1000
 - 27s - loss: 0.0283 - val_loss: 0.0281
Epoch 5/1000
 - 27s - loss: 0.0269 - val_loss: 0.0331
Epoch 6/1000
 - 26s - loss: 0.0261 - val_loss: 0.0303
Epoch 7/1000
 - 27s - loss: 0.0258 - val_loss: 0.0242
Epoch 8/1000
 - 27s - loss: 0.0244 - val_loss: 0.0256
Epoch 9/1000
 - 27s - loss: 0.0249 - val_loss: 0.0261
Epoch 10/1000
 - 27s - loss: 0.0235 - val_loss: 0.0265
Epoch 11/1000
 - 27s - loss: 0.0219 - val_loss: 0.0228
Epoch 12/1000
 - 27s - loss: 0.0215 - val_loss: 0.0216
Epoch 13/1000
 - 27s - loss: 0.0235 - val_loss: 0.0242
Epoch 14/1000
 - 27s - loss: 0.0212 - val_loss: 0.0239
Epoch 15/1000
 - 27s - loss: 0.0212 - val_loss: 0.0247
Epoch 16/1000
 - 27s - loss: 0.0245 - val_loss: 0.0259
Epoch 17/1000
 - 27s - loss: 0.0245 - val_loss: 0.0277
Epoch 00017: early sto

In [110]:
# Measure accuracy
pred = model.predict(x_test)
pred = np.argmax(pred,axis=1)
y_eval = np.argmax(y_test,axis=1)
score = metrics.accuracy_score(y_eval, pred)
print("Validation score: {}".format(score))

Validation score: 0.9961135176713494


In [208]:
train, test = train_test_split(x_pca,train_size = 0.25, test_size = 0.25)

In [37]:
scaled_data.shape


(494021, 38)

In [ ]:
train

In [153]:
#train_x.dtypes

In [20]:
model = LogisticRegression(random_state = 0, solver = 'lbfgs', multi_class = 'multinomial')

In [29]:
model.fit(scaled_data,y_train)

C:\Users\avmas\Miniconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [30]:
model.score(scaled_data,y_train)

0.9982470380813772

In [128]:
#Y["outcome"].groupby(Y["outcome"], axis = 0).count()

In [178]:
clf = DecisionTreeClassifier(random_state=0)

In [179]:
model = clf.fit(train_x,train_y)

In [180]:
model.score(train_x,train_y)

0.9999959515891025

In [162]:
x_reshape = train_x.reshape(-1,1)

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [156]:
from sklearn.metrics import classification_report

In [157]:
print(classification_report(train_x,train_y))

ValueError: Classification metrics can't handle a mix of continuous-multioutput and multiclass targets

array([[ 0.38652512,  1.16810165],
       [ 0.38962483,  1.14880423],
       [ 0.36900936,  1.12525357],
       ...,
       [-0.07885805,  1.19564015],
       [-0.29670041,  1.35722567],
       [-0.43117896,  1.3850602 ]])